proxy_cache_path /var/nginx/cache levels=1:2 keys_zone=my_cache:10m inactive=60m max_size=1g;
limit_req_zone $binary_remote_addr zone=req_limit:10m rate=5r/s;
limit_conn_zone $binary_remote_addr zone=conn_limit:10m ;

server {

 listen 443 ssl;
 server_name hospital.ahmedkabil.me;
 http2 on;
 ssl_certificate /etc/nginx/certs/hospital.ahmedkabil.me/fullchain.pem;
 ssl_certificate_key  /etc/nginx/certs/hospital.ahmedkabil.me/privkey.pem;
 ssl_protocols TLSv1.2 TLSv1.3;

 proxy_set_header Host $host;
 proxy_set_header X-Real-IP $remote_addr;

 location / {
    proxy_pass http://frontend:80;
    proxy_cache my_cache;
    proxy_cache_valid 200 60m;
    add_header X-Cache-Status $upstream_cache_status;

    limit_req zone=req_limit burst=3 nodelay ;
    limit_conn conn_limit 5 ;
 }

location ~ ^/api/(patients|staff|other) {
    proxy_pass http://core_service:7040;
}


location ~ ^/api/(conversations|messages|appointments) {
    proxy_pass http://chat_service:7030;
}


location /socket.io/ {
proxy_pass http://chat_service:7030;
# These three lines are critical for WebSockets
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}


location /api/readings {
proxy_pass http://iot_service:7020;
}

location /api/login {
proxy_pass http://auth_service:7010;
}

}

server {
    listen 80 ;
    server_name hospital.ahmedkabil.me;
    return 301 https://hospital.ahmedkabil.me;
}